
-- **************************************
-- Create account type
-- **************************************
CREATE TYPE public.account_type AS ENUM
('Client', 'Employee', 'Admin');

-- **************************************
-- Create classification table
-- **************************************
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name VARCHAR NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- **************************************
-- Create inventory table
-- **************************************
CREATE TABLE public.inventory(
    inv_id INT GENERATED BY DEFAULT AS IDENTITY,
    inv_make VARCHAR NOT NULL,
    inv_model VARCHAR NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image VARCHAR NOT NULL,
    inv_thumbnail VARCHAR NOT NULL,
    inv_price NUMERIC NOT NULL,
    inv_year INT NOT NULL,
    inv_miles INT NOT NULL, 
    inv_color VARCHAR NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT inventory_pk PRIMARY KEY (inv_id)
);

-- **************************************
-- Create account table
-- **************************************
CREATE TABLE public.account(
    account_id INT GENERATED BY DEFAULT AS IDENTITY,
    account_firstname VARCHAR NOT NULL,
    account_lastname VARCHAR NOT NULL,
    account_email VARCHAR NOT NULL,
    account_password VARCHAR NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client',
    CONSTRAINT account_pk PRIMARY KEY (account_id)
);

-- **************************************
-- Foreign key relationship
-- **************************************

ALTER TABLE public.inventory
ADD CONSTRAINT fk_classification
FOREIGN KEY (classification_id)
REFERENCES public.classificatioN(classification_id)
ON UPDATE CASCADE;

-- **************************************
-- Insert classification data
-- **************************************
INSERT INTO public.classification (classification_name)
VALUES
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- **************************************
-- Insert inventory data
-- **************************************
INSERT INTO public.inventory(
    inv_make, inv_model, inv_description, inv_image,
    inv_thumbnail, inv_price, inv_year, inv_miles,
    inv_color, classification_id
)VALUES
    ('GM', 'Hummer', 'A large vehicle with small interiors.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 45000, 2018, 25000, 'Black', 3),
    ('Chevy', 'Camaro', 'A fast sport vehicle.', '/images/camaro.jpg', '/images/camaro-tn.jpg', 35000, 2020, 15000, 'Red', 2),
    ('Ford', 'Mustang', 'Classic American muscle car.', '/images/mustang.jpg', '/images/mustang-tn.jpg', 40000, 2019, 20000, 'Blue', 2);


SELECT * FROM inventory
-- **************************************
-- Task 4 query (copied from assignment2.sql)
-- **************************************
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM'
AND inv_model = 'Hummer';

-- **************************************
-- Task 6 query (copied from assignment2.sql)
-- **************************************
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
     inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

SELECT * FROM classification;
SELECT * FROM inventory;
SELECT * FROM inventory;